/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_changhr_learn_jni_Sort */

#ifndef _Included_com_changhr_learn_jni_Sort
#define _Included_com_changhr_learn_jni_Sort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_changhr_learn_jni_Sort
 * Method:    selectionSort
 * Signature: ([II)[I
 */
JNIEXPORT jintArray JNICALL Java_com_changhr_learn_jni_Sort_selectionSort___3II
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     com_changhr_learn_jni_Sort
 * Method:    selectionSort
 * Signature: ([FI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_changhr_learn_jni_Sort_selectionSort___3FI
  (JNIEnv *, jobject, jfloatArray, jint);

#ifdef __cplusplus
}
#endif
#endif
